### ISSUE TITLE
Crashes around the cactus.

### ISSUE THREAD

**Issue by e5frog** [AlexeyMatrosov/RetroDino#2]
Suggest drawing Dino after cactus, so it would be possible to see that it hits, with the blue area around the cactus it looks as if he hits air. 
Not sure if you use the clear pixels, then it's possible to draw like so:
cactus: clear/green
dino: clear/blue
cactus: clear/bkg to erase
cactus: clear/green in new position
dino: clear/bkg to erase 
dino: clear/blue to draw in new position
repeat

It depends on how much you need to do in between, using a box in bkg/object color is of course faster and easier.

... or maybe I just need to practice more.   ;-)

**Comment by AlexeyMatrosov** [comment]
I have added animation similar to the one you suggested
